language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python manage.py test apps
deploy:
  provider: heroku
  api_key:
    secure: $GITHUB_TOKEN
    app: main
  on:
    repo: atakangol/webProjectMovieDB
    branch: master
