# Generated by Django 3.0.3 on 2020-02-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Genres')),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movies')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.People')),
            ],
        ),
    ]
