# Generated by Django 3.0.3 on 2020-03-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200226_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListID', models.IntegerField(unique=True)),
                ('Date', models.DateTimeField()),
                ('Rating', models.IntegerField()),
                ('Public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Umail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='List_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('ListID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.List')),
                ('MovieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='ListOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.CreateModel(
            name='Favorite_Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
