# Generated by Django 3.0.3 on 2020-02-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreID', models.IntegerField()),
                ('genreName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleId', models.IntegerField(unique=True)),
                ('Pname', models.CharField(max_length=50)),
                ('Pbirth', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.IntegerField(unique=True)),
                ('movieName', models.CharField(max_length=30)),
                ('movieYear', models.IntegerField()),
                ('directorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.People')),
            ],
        ),
    ]
