# Generated by Django 3.0.3 on 2020-05-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200504_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_movie',
            name='favoriteCharacter',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
