# Generated by Django 3.0.3 on 2020-05-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_favorite_movie_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite_movie',
            old_name='user',
            new_name='userID',
        ),
    ]
