# Generated by Django 3.0.3 on 2020-05-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200505_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_movie',
            name='favoriteCharacter',
        ),
        migrations.AddField(
            model_name='favorite_movie',
            name='favActorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
