# Generated by Django 3.0.3 on 2020-05-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200505_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_movie',
            name='movieName',
        ),
    ]
