# Generated by Django 3.0.3 on 2020-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_favorite_movie_moviename'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_movie',
            name='movieName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
