# Generated by Django 3.0.3 on 2020-05-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_favorite_movie_moviename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_movie',
            name='movieName',
        ),
    ]
