# Generated by Django 3.0.3 on 2020-05-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_favorite_movie_moviename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casting',
            name='order',
        ),
        migrations.AlterField(
            model_name='favorite_movie',
            name='favActorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Casting'),
        ),
    ]
